name: Sync repo to NUHS repo

on:
  workflow_dispatch:

env:
  GH_SECRET: ${{ secrets.GH_SECRET }}
jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Sync
      run: |
        echo "Hello ${{ inputs.source_repo }}"
        echo "Hello ${{ inputs.dest_repo }}"
        echo "${{ github.workspace }}"
        echo "$GITHUB_WORKSPACE"
        ls -al
        mkdir nuhs_sync;cd nuhs_sync
        git clone --bare "https://github.com/ncmuthu/synctest01.git"
        cd synctest01.git
        echo "..Mirroring the repo to https://github.com/${{ inputs.dest_repo }}"
        git push --mirror "https://ncmuthu:$GH_SECRET@github.com/ncmuthu/synctestdest01.git"
