name: Sync GitHub Repos

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'source repository'
        default: 'https://github.com/ncmuthu/synctest01.git'
        required: true
        type: string
      dest_repo:
        description: 'destination repository'
        default: 'https://github.com/ncmuthu/synctestdest01.git'
        required: true
        type: string

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Sync
      run: |
        echo "Hello ${{ inputs.source_repo }}"
        echo "Hello ${{ inputs.dest_repo }}"
        echo "${{ github.workspace }}"
        echo "$GITHUB_WORKSPACE"
        ls -al
        mkdir nuhs_sync;cd nuhs_sync
        git clone --bare ${{ inputs.source_repo }}
        cd synctest01.git
        echo "..Mirroring the repo to ${{ inputs.dest_repo }}"
        git push --mirror https://ncmuthu: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@github.com/ncmuthu/synctestdest01.git
