name: Sync GitHub Repos

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'source repository'
        default: 'World'
        required: true
        type: string
      dest_repo:
        description: 'destination repository'
        default: 'World'
        required: true
        type: string

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Sync
      run: |
        cd ${{ 
        echo "Hello ${{ inputs.source_repo }}"
        echo "Hello ${{ inputs.dest_repo }}"
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE
